services:
  ingress:
    build:
      context: ../..
      dockerfile: samples/demo/Dockerfile
    command: Ingress
    ports:
      - "6224:6224"
    environment:
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "6224"

  galaxy:
    build:
      context: ../..
      dockerfile: samples/demo/Dockerfile
    command: Galaxy
    environment:
      GALAXY_HOST: "0.0.0.0"
      GALAXY_PORT: "62200"
      GALAXY_NAME: "production"
      GALAXY_ADVERTISE_HOST: "galaxy"
      INGRESS_HOST: "ingress"
      INGRESS_PORT: "6224"
    depends_on:
      - ingress

  stellar:
    build:
      context: ../..
      dockerfile: samples/demo/Dockerfile
    command: Stellar
    ports:
      - "62300:62300"
    environment:
      STELLAR_HOST: "0.0.0.0"
      STELLAR_PORT: "62300"
      STELLAR_NAME: "Embedding"
      STELLAR_NAMESPACE: "production.ml.embedding"
      GALAXY_HOST: "galaxy"
      GALAXY_PORT: "62200"
    depends_on:
      - galaxy
